apiVersion: v1
kind: ConfigMap
metadata:
  name: diverciphy-config
data:
  # Configuration exposed to all deployments
  # Note: The worker list here is static for simplicity, or managed via DNS in active code
  SHREDDER_ADRESSES: '["http://worker-0.d-svc:5000", "http://worker-1.d-svc:5000", "http://worker-2.d-svc:5000", "http://worker-3.d-svc:5000", "http://worker-4.d-svc:5000", "http://worker-5.d-svc:5000", "http://worker-6.d-svc:5000", "http://worker-7.d-svc:5000", "http://worker-8.d-svc:5000", "http://worker-9.d-svc:5000"]'
  MASTER_ASSEMBLER_URL: "http://master-assembler:5556"
  MASTER_ADDRESS: "http://master-shredder:5555"
  SHREDDER_ADDRESS: "http://master-shredder:5555"

---
apiVersion: v1
kind: Secret
metadata:
  name: diverciphy-secret
type: Opaque
stringData:
  # In production, these should be injected or sealed
  JWT_SECRET_KEY: "change_me_production_secret"
  FILE_PASSWORD: "super_secure_file_password"
